name: "Build&Deploy MOVAI Ignition Gazebo"

on:
  # Trigger the workflow on push or pull request
  # but only for the main branch
  # or on tag of type v*.*.*
  push:
    branches:
      - main
      - dev
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - main
      - dev
  release:
    types: [released]
jobs:
  ignition-gazebo:
    uses: MOV-AI/.github/.github/workflows/docker-workflow.yml@v2
    with:
      docker_file: gazebo/Dockerfile
      docker_image: devops/ignition-gazebo
      public: true
      public_image: ce/ignition-gazebo
      deploy: ${{ contains(github.ref, 'refs/heads/main') || contains(github.ref, 'refs/tags/v')}}
      push_latest: ${{ contains(github.ref, 'refs/heads/main') || contains(github.ref, 'refs/tags/v') }}
      snyk_check: true
      platforms: linux/amd64, linux/arm/v7, linux/arm64
    secrets:
      registry_user: ${{ secrets.PORTUS_APP_USER }}
      registry_password: ${{ secrets.PORTUS_APP_TOKEN }}
      pub_registry_user: ${{ secrets.PORTUS_APP_USER }}
      pub_registry_password: ${{ secrets.PORTUS_APP_TOKEN }}
      github_registry_user: ${{ secrets.RAISE_BOT_COMMIT_USER }}
      github_registry_password: ${{ secrets.RAISE_BOT_COMMIT_PASSWORD }}
      snyk_token: ${{ secrets.SNYK_TOKEN }}
